# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TravelAndEntertainment' do
# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!
pod 'Alamofire'
pod 'AlamofireSwiftyJSON'
pod 'McPicker'
pod 'EasyToast'
pod 'Cosmos'
pod 'SwiftSpinner'
pod 'GooglePlaces'
pod 'GooglePlacePicker'
pod 'GoogleMaps'

# Pods for TravelAndEntertainment

end
